---
title: "Belarus 2020"
author: "Kristýna Bednářová"
format: html
editor: source
---

```{r setup}
cfg <- config::get()
source(cfg$library)


data <- read.csv(file.path(cfg$data, "Belarus-2020", "Protocol_data.csv"))

vec <- c(data$Dmitriev, data$Konopackaya, data$Lukashenko, data$Tsikhanouskaya, data$Cherechen)
vec <- vec[!is.na(vec) & !vec == 0] #NA jsou vlastne 0 takze to je v pohode
```

```{r}
OMV(vec)
OOM(vec)
```


```{r}
first_digits <- digits(vec, first = 1)
BL_leading_digit_table(first_digits)
compliance_test_chisq(first_digits)
plot_BL_RelFreq_bar(first_digits)
save_png("USA24-celkem-first_digits")


plot_BL_RelFreq_bar(digits(data$Lukashenko, first = 1)) + 
  plot_BL_RelFreq_bar(digits(data$Dmitriev, first = 1)) + 
  plot_BL_RelFreq_bar(digits(data$Konopackaya, first = 1)) + 
  plot_BL_RelFreq_bar(digits(data$Tsikhanouskaya, first = 1)) + 
  plot_BL_RelFreq_bar(digits(data$Cherechen, first = 1)) + 
  plot_layout(guides = "collect")
```


```{r}
# last_digits <- digits(data$total_votes, last = 1)
# BL_last_digit_table(last_digits)
# compliance_test_chisq(last_digits, last = T)
# plot_BL_RelFreq_bar(last_digits, last = T)
# save_png("USA24-celkem-last_digits")
# 
# first_two_digits <- digits(data$total_votes, first = 2)
# BL_leading_digit_table(first_two_digits)
# compliance_test_chisq(first_two_digits)
# plot_BL_RelFreq_bar(first_two_digits)
# save_png("USA24-celkem-first_two_digits")
# 
# last_two_digits <- digits(data$total_votes, last = 2)
# BL_last_digit_table(last_two_digits)
# compliance_test_chisq(last_two_digits, last = T)
# plot_BL_RelFreq_bar(last_two_digits, last = T)
# save_png("USA24-celkem-last_two_digits")
# 
# 
# OMV(data$votes_dem)
# OOM(data$votes_dem)
# 
# OMV(data$votes_gop)
# OOM(data$votes_gop)
# 
# 
# dualplot_BL_RelFreq_bar(A = digits(data$votes_gop, first = 1), A_title = "Republicans", 
#                         B = digits(data$votes_dem, first = 1), B_title = "Democrats", 
#                         last = F)
# save_png("USA24-dual-first_digits")
# 
# dualplot_BL_RelFreq_bar(A = digits(data$votes_gop, first = 2), A_title = "Republicans", 
#                         B = digits(data$votes_dem, first = 2), B_title = "Democrats", 
#                         last = F, max = 0.052)
# save_png("USA24-dual-first_two_digits")
# 
# dualplot_BL_RelFreq_bar(A = digits(data$votes_gop, last = 1), A_title = "Republicans", 
#                         B = digits(data$votes_dem, last = 1), B_title = "Democrats", 
#                         last = T, max = 0.12)
# save_png("USA24-dual-last_digits")
# 
# dualplot_BL_RelFreq_bar(A = digits(data$votes_gop, last = 2), A_title = "Republicans", 
#                         B = digits(data$votes_dem, last = 2), B_title = "Democrats", 
#                         last = T, max = 0.0155)
# save_png("USA24-dual-last_two_digits")


```

