---
title: "USA24-outputs"
format: html
editor: source
---

```{r setup}
cfg <- config::get()
source(cfg$library)

# analysis on the city level + foreign vote counts 
data <- read.csv(file.path(cfg$data, "USA-2024",
                           "2024_US_County_Level_Presidential_Results.csv"), 
                 header = T, sep = ",")

A <- data$votes_gop
B <- data$votes_dem 
A_title <- "Donald Trump"
B_title <- "Kamala Harris"
numbers <- c(A, B)
both <- c(A, B)
```


## all votes 

```{r both first position}
first <- digits(numbers, first = 1)
plot_BL_RelFreq_bar(digits(numbers, first = 1))
save_pdf("USA24-both-first_digits")
```

```{r both first two digits}
plot_BL_RelFreq_bar(digits(numbers, first = 2))
save_pdf("USA24-both-first_two_digits")
```

```{r both second position}
plot_BL_RelFreq_bar(digits_on_position(numbers, 2, na.rm = T), position = 2)
save_pdf("USA24-both-second_digits")
```


```{r both last}
plot_BL_RelFreq_bar(digits(numbers, last = 1), last = T)
save_pdf("USA24-both-last_digits")
```


```{r both third position}
plot_BL_RelFreq_bar(digits_on_position(numbers, position = 3, na.rm = T), position = 3)
save_pdf("USA24-both-third_digits")
```

```{r both fourth position} 
# we have large enough numbers (vote counts), so we can observe how the relative frequencies of the fourth digits comply with BL for the fourth position 
plot_BL_RelFreq_bar(digits_on_position(numbers, position = 4, na.rm = T), position = 4)
# save_pdf("USA24-both-fourth_digits")
```


```{r both, eval = F}
plot_BL_RelFreq_bar(digits_on_position(numbers, position = 5, na.rm = T), position = 5)
plot_BL_RelFreq_bar(digits_on_position(numbers, position = 6, na.rm = T), position = 6)
```

## per candidate

```{r dualplot}
dualplot_BL_RelFreq_bar(A = digits(A, first = 1), A_title = A_title, 
                        B = digits(B, first = 1), B_title = B_title, 
                        last = F)
save_pdf("USA24-dual-first_digits")
```


```{r dualplot}
dualplot_BL_RelFreq_bar(digits(A, first = 2), A_title, 
                        digits(B, first = 2), B_title, 
                        last = F, max = 0.05)
save_pdf("USA24-dual-first_two_digits")
```


```{r dualplot}
dualplot_BL_RelFreq_bar(digits_on_position(A, position = 2, na.rm = T), A_title, position = 2, 
                        digits_on_position(B, position = 2, na.rm = T), B_title, 
                        last = F, max =0.15)
save_pdf("USA24-dual-second_digits")
```

```{r dualplot}
dualplot_BL_RelFreq_bar(digits_on_position(A, position = 3, na.rm = T), A_title, position = 3, 
                        digits_on_position(B, position = 3, na.rm = T), B_title, 
                        last = F, max =0.12)
save_pdf("USA24-dual-third_digits")
```


```{r dualplot}
dualplot_BL_RelFreq_bar(digits_on_position(A, position = 4, na.rm = T), A_title, position = 4, 
                        digits_on_position(B, position = 4, na.rm = T), B_title, 
                        last = F, max = 0.108)
# save_pdf("USA24-dual-fourth_digits")
```


```{r dualplot}
dualplot_BL_RelFreq_bar(digits(A, last = 1), A_title, 
                        digits(B, last = 1), B_title, 
                        last = T, max = 0.118)
save_pdf("USA24-dual-last_digits")
```


# digital development pattern 
```{r}
table_ddp <- ddp_table(numbers, intervals = intervals[1:7]) 
table_dig <- table_ddp[-c(1,2,12,13),]
table_dig <- data.frame(table_dig) |> mutate(digit = 1:9, 
                                             X1 = ifelse(is.na(X1), 0, X1), 
                                             X7 = ifelse(is.na(X7), 0, X7))

table_dig |> 
  pivot_longer(cols = c("X1", "X2","X3", "X4","X5", "X6", "X7"), names_to = 'order', values_to = 'relative frequency') |> 
  ggplot(aes(x = digit, y = `relative frequency`)) + 
  geom_bar(stat = 'identity', position = 'dodge', fill = barvy$VSE['darkpink']) + 
  scale_x_continuous(n.breaks = 10) +
  #ggtitle("Digital development pattern") + 
  facet_grid(.~order, labeller = 
               labeller(order = c(X1 = paste('1<=X<10\n', round(table_ddp[13,1],2), "%"), 
                                  X2 = paste("10<=X<100\n",  round(table_ddp[13,2],2), "%"),
                                  X3 = paste('100<=X<1000\n',  round(table_ddp[13,3],2), "%"),
                                  X4 = paste("10^3<=X<10^4\n",  round(table_ddp[13,4],2), "%"),
                                  X5 = paste('10^4<=X<10^5\n', round(table_ddp[13,5],2), "%"), 
                                  X6 = paste('10^5<=X<10^6\n', round(table_ddp[13,6],2), "%"), 
                                  X7 = paste('10^6<=X<10^7\n', round(table_ddp[13,6],2), "%")
                                  ))) + 
  theme_BL(legend.position = 'none') 

save_pdf("USA24-digital_development_pattern")

```

